apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-event
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-event/overlays/dev
    repoURL: https://github.com/hsqlu/control-apps
    targetRevision: main
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true